;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-backward-char
        evil-change
        evil-delete
        paredit-forward-kill-word
        smex
        ))

(setq mc/cmds-to-run-once
      '(
        evil-substitute
        ))
