#+TITLE:    Bogdan's EMACS Config
#+AUTHOR:   Bogdan Popa
#+EMAIL:    popa.bogdanp@gmail.com
#+LANGUAGE: en
#+STARTUP:  showall

* This Document
  The purpose of this document is mostly to help me remember all of my
  settings as well as to help newbies set up their environment and get
  started using my configuration.

* Installation
** Linux
   This depends on the distribution. Most of them will have EMACS in
   their repositories.

   #+BEGIN_SRC sh
     sudo apt-get install emacs-snapshot-gtk
   #+END_SRC

** Mac OS X
   Download and install EMACS for OS X from [[http://emacsformacosx.com][EMACS for Mac OS X]].

** Windows
   Download and install EMACS for Windows from the [[http://ftp.gnu.org.ua/gnu/emacs/windows/][GNU Repositories]].

* Setup
** Unix
   Clone the repo into your home directory and then fetch its
   submodules.

   #+BEGIN_SRC sh
     cd ~/
     git clone https://github.com/Bogdanp/.emacs.d.git
     cd .emacs.d
     git submodule init
     git submodule update
   #+END_SRC

** Windows
   Windows makes things a bit harder. Add an environment variable
   called =HOME= and make it point to =C:/Users/Username/=. Clone the
   =windows= branch of the repository in that folder and fetch its
   submodules.

* Bindings
  The most important EMACS binding is =C-g=. Use it as an escape hatch
  for when you mess up your key combinations.

  - =q= will close most popups, make sure you are in EMACS mode before
    you use it (you're in EMACS mode if there's an =<E>= in your
    status bad).
  - =C-p= and =C-n= goto next and prev line.
  - =C-a= and =C-e= goto the beginning and end of the current line.
  - =M-x= command mode.
  - =C-x b= switch buffer.
  - =C-x f= find file.
  - =C-x o= switch to other window.
  - =C-c M-a= toggle between the current window state and a
    fullscreen terminal.

* Backups
  =undo-tree-mode= is enabled globally. All backups - including
  =undo-tree= files - are saved in =temporary-file-directory=.

* dired+
  You can bring up dired by pressing =C-j= on a folder whilst in
  =ido-find-file= (=C-x C-f=).

** Bindings
   - =+= create directory.
   - =d= delete file(s).
   - =g= refresh buffer.
   - =m= mark file.
   - =u= unmark file.
   - =R= rename file(s).
   - =U= unmark all files.
   - =M-<= goto beginning of buffer.
   - =M->= goto end of buffer.

* EVIL
** Differences From Standard EVIL
   My EVIL mode fork makes some changes to the way registers are
   handled. Most importantly, while you are inside an EVIL mode
   buffer you can only access the clipboard through the =+= register
   and nothing else, this prevents EMACS from dirtying the clipboard
   whenever you cut things.

   The copy-on-motion bug is fixed.

   =C-w= now works in the minibuffer.

** Common Bindings
   You can drop into EMACS mode for a single command using ~\~.

   - =C-z= switch between EVIL and EMACS mode.

** Normal Mode Bindings
   - =SPC= bring up ace jump mode.
   - =S-SPC= bring up ace char jump mode.
   - =C-w f= toggle between making the current window fullscreen or not.

** Visual Mode Bindings
   The =C-a=, =C-e=, =C-p=, =C-n= bindings are available in visual
   mode.

** Insert Mode Bindings
   The =C-a=, =C-e=, =C-p=, =C-n= bindings are available in insert
   mode.

   - =C-w= deletes the previous word.
   - =C-r= inserts whatever is in a given buffer.

* Magit
  Magit is fucking great. You can find its official manual [[http://magit.github.io/master/magit.html][here]].

** Generic Bindings
   - =n= goto next object.
   - =p= goto previous object.
   - =TAB= expand/collapse object.
   - =RET= open object.

** Status Bindings
   Use =C-c m= to bring =magit-status= up.

   - =S= stage everything.
   - =s= stage object under point.
   - =u= unstage object under point.
   - =b*= branch operations.
   - =c*= commit operations.
   - =f*= fetch operations.
   - =F*= pull operations.
   - =P*= push operations.

** Branch Bindings
   Use =bv= inside =magit-status= to bring up the visual branch manager.

* Org
** Bindings
   - =TAB= toggle headings.
   - =S-TAB= toggle headings globally.
   - =C-c=' in a source code block will open up the code in a
     separate buffer for editing.
   - =C-c .= insert date.
   - =C-c C-u= parent heading.
   - =C-c C-b= previous same-level heading.
   - =C-c C-f= next same-level heading.
   - =C-c C-p= previous heading.
   - =C-c C-n= next heading.
   - =C-c C-e= export document.
   - =C-x n s= narrow buffer.
   - =C-x n w= widen buffer.
   - =C-RET= add new heading at the current level.
   - =M-RET= add new heading/list item at the current level.
   - =M-→= increase heading level.
   - =M-←= decrease heading level.
   - =S-M-→= increase heading level incl. children.
   - =S-M-←= decrease heading level incl. children.

* Prodigy
  Prodigy is bound to =C-c p=.

** Services
   Services should be defined in =config/init-prodigy.el=. The
   following is an example service:

   #+BEGIN_SRC elisp -n -r
     (prodigy-define-service
       :name "Python Server"
       :command "python"
       :args '("-m" "SimpleHTTPServer" "8093")
       :cwd "/path/to/my/project/"
       :tags '(example)
       :kill-process-buffer-on-stop t)
   #+END_SRC

** Bindings
   - =s= start a process.
   - =S= stop a process.
   - =r= restart a process.
   - =$= open a process' log.
   - =F= clear filters.
   - =f t= filter by tag.
   - =f n= filter by name.
   - =j d= open dired for the current process.
   - =j m= open magit for the current process.

* Haskell
  You will need a recent version of =ghc= and =cabal= as well as the
  following packages: =hlint=, =ghc-mod=, =ghci-ng=,
  =structured-haskell-mode=, =stylish-haskell=.

** Structured Haskell Mode
   See the [[https://github.com/chrisdone/structured-haskell-mode][Official Repository]].

** Bindings
   - =C-c C-l= load the current source file into a REPL.
   - =C-c C-t= show type of object at point.

* PHP
  PHP is supported through =php-mode= and =web-mode=. Use =web-mode=
  for mixed HTML and PHP files and =php-mode= for pure PHP files. The
  default mode for PHP files is =web-mode=.

** Flycheck
   Install =phpcs= from PEAR and you should be good to go.

* Python
** Flycheck
   Install =flake8= to use it as a backend for Flycheck.

*** Ignoring Certain Errors
    Create a =.flake8rc= file in your =HOME= directory. For example:

    #+NAME: .flake8rc
    #+BEGIN_SRC conf -n -r
      [flake8]
      ignore = E501,F403,E712
    #+END_SRC

*** Bindings
    - =C-c !n= and =C-c !p= goto next and prev error.
    - =C-c !l= list errors.

** Jedi
   Install =virtualenv= and =epc= and then run =M-x jedi:install-server=.

*** Bindings
    - =C-c .= goto definition (and =C-c= ,).
    - =C-c ?= show documentation of the object at point.

* Scala
  View the ENSIME manual at the [[https://github.com/ensime/ensime-src][Official Repository]]. Start up ENSIME
  in a Scala buffer with =M-x ensime RET=.

* Scheme
** Setup
   Link =mzscheme= and =racket= so that they can be found in =PATH=.

** Geiser mode
   Start it up with =M-x run-geiser=.

*** Buffer Bindings
    - =C-c C-a= to switch to the REPL and enter the current module.
    - =C-c C-z= to switch between the buffer and the REPL.
    - =C-M-x= eval definition around point.
    - =C-c M-e= eval definition around point and switch to REPL.
    - =C-c C-x= eval sexp before point.
    - =C-c C-r= eval region (also =C-c M-r=).
    - =C-c C-b= eval buffer (also =C-c M-b=).
    - =M-g n= and =M-g p= to jump to next and prev error.

*** REPL Bindings
    - =C-c C-q= kill Scheme process.
    - =C-c M-o= clear REPL.
